#!/usr/bin/env python3
"""Generate the Hockeystick Android launcher icon and splash mark.

One source of geometry -> SVG previews (for eyeballing / PNG rendering) and
Android VectorDrawables (what actually ships in the APK). The mark is the same
long-call payoff curve as brand/logo-badge.svg: a flat capped-loss leg hinging
into an uncapped rising leg, with the riso cyan misregistration behind it.
"""
import os, pathlib

INK   = "#14150F"
VOLT  = "#D8EE2E"
CYAN  = "#5FE3FF"
PAPER = "#EDEEE4"

# --- mark geometry, in the brand's 0 0 100 100 box -------------------------
KNEE_X, BASE_Y = 49.0, 67.0      # hinge
START_X        = 20.0            # left end of the flat leg
TIP_X, TIP_Y   = 80.0, 30.0      # top of the rising leg
SW             = 9.5             # stroke width
RULE_X0, RULE_X1 = 11.0, 89.0    # the dotted zero line
RULE_SW, DASH_ON, DASH_OFF = 1.4, 2.5, 3.5
GHOST = -2.4                     # cyan offset, x and y

CANVAS = 108.0                   # adaptive-icon canvas
CONTENT_W = 66.0                 # how wide the mark sits inside it

# Content bounds including stroke geometry and the ghost offset.
# Rising leg ends with a butt cap perpendicular to its direction.
import math
dx, dy = TIP_X - KNEE_X, TIP_Y - BASE_Y
L = math.hypot(dx, dy)
px, py = -dy / L * SW / 2, dx / L * SW / 2      # half-cap vector at the tip
X0 = min(RULE_X0, START_X + GHOST)
X1 = max(RULE_X1, TIP_X + abs(px))
Y0 = min(TIP_Y - abs(py) + GHOST, BASE_Y - SW / 2 + GHOST)
Y1 = max(BASE_Y + SW / 2, BASE_Y + RULE_SW / 2)

S  = CONTENT_W / (X1 - X0)
TX = CANVAS / 2 - S * (X0 + X1) / 2
TY = CANVAS / 2 - S * (Y0 + Y1) / 2
fx = lambda x: round(S * x + TX, 2)
fy = lambda y: round(S * y + TY, 2)
fs = lambda v: round(S * v, 2)

STICK = f"M{fx(START_X)},{fy(BASE_Y)} H{fx(KNEE_X)} L{fx(TIP_X)},{fy(TIP_Y)}"
GHOST_STICK = (f"M{fx(START_X + GHOST)},{fy(BASE_Y + GHOST)} "
               f"H{fx(KNEE_X + GHOST)} L{fx(TIP_X + GHOST)},{fy(TIP_Y + GHOST)}")
STROKE = fs(SW)

def dotted_rule():
    """VectorDrawable has no stroke-dasharray, so the zero line is emitted as
    explicit segments. Same path data then works in SVG and in the APK."""
    segs, x, period = [], RULE_X0, DASH_ON + DASH_OFF
    n = max(1, round((RULE_X1 - RULE_X0) / period))
    period = (RULE_X1 - RULE_X0) / n
    on = period * DASH_ON / (DASH_ON + DASH_OFF)
    for i in range(n):
        x = RULE_X0 + i * period
        segs.append(f"M{fx(x)},{fy(BASE_Y)} H{fx(x + on)}")
    return " ".join(segs)

RULE = dotted_rule()
RULE_STROKE = fs(RULE_SW)

# --- emitters ---------------------------------------------------------------
def svg_mark(rule_color, rule_alpha):
    return f'''  <path d="{RULE}" stroke="{rule_color}" stroke-opacity="{rule_alpha}" stroke-width="{RULE_STROKE}" fill="none"/>
  <path d="{GHOST_STICK}" stroke="{CYAN}" stroke-opacity="0.9" stroke-width="{STROKE}" stroke-linecap="butt" stroke-linejoin="miter" fill="none"/>
  <path d="{STICK}" stroke="{VOLT}" stroke-width="{STROKE}" stroke-linecap="butt" stroke-linejoin="miter" fill="none"/>'''

def svg(body, bg=None, size=CANVAS):
    ground = f'<rect width="{CANVAS}" height="{CANVAS}" fill="{bg}"/>' if bg else ""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
            f'viewBox="0 0 {CANVAS:g} {CANVAS:g}" fill="none">\n  {ground}\n{body}\n</svg>\n')

def vector(body, w=CANVAS, h=CANVAS):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand/src/android_icon.py — edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{w:g}dp"
    android:height="{h:g}dp"
    android:viewportWidth="{w:g}"
    android:viewportHeight="{h:g}">
{body}
</vector>
'''

def vpath(d, color, width, alpha=None, cap="butt", join="miter"):
    a = f'\n        android:strokeAlpha="{alpha}"' if alpha is not None else ""
    return (f'    <path\n        android:pathData="{d}"\n'
            f'        android:strokeColor="{color}"\n'
            f'        android:strokeWidth="{width}"{a}\n'
            f'        android:strokeLineCap="{cap}"\n'
            f'        android:strokeLineJoin="{join}"/>')

ROOT = pathlib.Path(__file__).resolve().parents[2]
RES  = ROOT / "android/app/src/main/res"
OUT  = ROOT / "brand/android"
OUT.mkdir(parents=True, exist_ok=True)

# 1. Adaptive icon layers.
(RES / "drawable/ic_launcher_background.xml").write_text(vector(
    f'    <path\n        android:pathData="M0,0h{CANVAS:g}v{CANVAS:g}h-{CANVAS:g}z"\n'
    f'        android:fillColor="{INK}"/>'))

fg = "\n".join([
    vpath(RULE, PAPER, RULE_STROKE, alpha="0.24"),
    vpath(GHOST_STICK, CYAN, STROKE, alpha="0.9"),
    vpath(STICK, VOLT, STROKE),
])
(RES / "drawable/ic_launcher_foreground.xml").write_text(vector(fg))

# Themed (monochrome) icon: one flat silhouette, tinted by the launcher.
(RES / "drawable/ic_launcher_monochrome.xml").write_text(vector("\n".join([
    vpath(RULE, "#FFFFFF", RULE_STROKE, alpha="0.4"),
    vpath(STICK, "#FFFFFF", STROKE),
])))

# 2. The splash mark, drawn on the app's ink ground.
(RES / "drawable/splash_mark.xml").write_text(vector(fg))

# 3. SVG previews.
(OUT / "icon-square.svg").write_text(svg(svg_mark(PAPER, "0.24"), bg=INK, size=512))
(OUT / "icon-transparent.svg").write_text(svg(svg_mark(PAPER, "0.24"), size=512))

print("mark scale", round(S, 4), "content", round(X1 - X0, 2), "x", round(Y1 - Y0, 2))
print("stick", STICK)
print("stroke", STROKE, "rule segments", RULE.count("M"))
for p in sorted(list(RES.rglob("*.xml")) + list(OUT.glob("*.svg"))):
    print(" ", p.relative_to(ROOT))

# 4. A preview sheet, for eyeballing the icon before it ships.
def cell(inner, cap):
    return f'<div class="cell">{inner}<div class="cap">{cap}</div></div>'

def tile(px, cls):
    return (f'<div class="ic {cls}" style="width:{px}px;height:{px}px">'
            f'{svg(svg_mark(PAPER, "0.24"), size=px)}</div>')

masks = "".join(cell(tile(200, c), n) for c, n in
                [("circle", "Circle"), ("squircle", "Squircle"),
                 ("round", "Rounded"), ("sq", "Full bleed")])
sizes = "".join(cell(tile(px, "squircle"), n) for px, n in
                [(144, "xxhdpi 144"), (96, "xhdpi 96"), (72, "hdpi 72"),
                 (48, "mdpi 48"), (32, "notification 32")])
splash = cell(
    '<div class="phone">' + svg(svg_mark(PAPER, "0.24"), size=150) +
    '<div class="wm">Hockeystick</div></div>',
    "Cold start — logo, then the app")

(OUT / "preview.html").write_text(f'''<!doctype html><meta charset="utf-8">
<style>
  *{{margin:0;padding:0;box-sizing:border-box}}
  body{{background:{PAPER};font:13px/1.4 -apple-system,Helvetica,sans-serif;color:{INK};
       width:1200px;padding:48px 56px}}
  h1{{font-size:11px;letter-spacing:.18em;text-transform:uppercase;opacity:.5;margin-bottom:28px}}
  .row{{display:flex;align-items:flex-end;gap:44px;margin-bottom:44px}}
  .cap{{margin-top:12px;font-size:10px;letter-spacing:.1em;text-transform:uppercase;opacity:.45}}
  .cell{{text-align:center}}
  .ic{{background:{INK};overflow:hidden}}
  .circle{{border-radius:50%}} .squircle{{border-radius:22.5%}} .round{{border-radius:14%}}
  .phone{{width:300px;height:600px;background:{INK};border-radius:34px;
         display:grid;place-items:center;position:relative;overflow:hidden}}
  .phone .wm{{position:absolute;bottom:38px;font-size:10px;letter-spacing:.22em;
             text-transform:uppercase;color:{PAPER};opacity:.38}}
  hr{{border:0;border-top:1px solid rgba(20,21,15,.16);margin:8px 0 36px}}
</style>
<h1>Hockeystick — Android launcher icon</h1>
<div class="row">{masks}</div><hr>
<h1>Legibility at real launcher sizes</h1>
<div class="row">{sizes}</div><hr>
<h1>Splash</h1>
<div class="row">{splash}</div>
''')
print("  brand/android/preview.html")
